Ecommerce_site/App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name='add'),
    path('remove/<pk>/', views.remove_from_cart, name='remove'),
    path('cart/', views.cart_view, name='cart'),
    path('increase/<pk>/', views.increase_cart, name='increase'),
    path('decrease/<pk>/', views.decrease_cart, name='decrease'),
]

Ecommerce_site/App_Payment/urls.py
from django.urls import path
from App_Payment import views

app_name="App_Payment"

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('pay/', views.payment, name='payment'),
    path('status/', views.complete, name='complete'),
    path('purchase/<val_id>/<tran_id>/', views.purchase, name='purchase'),
    path('orders/', views.order_view, name='orders'),
]

Ecommerce_site/App_Shop/urls.py
from django.urls import path
from App_Shop import views


app_name = 'App_Shop'



urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
    path('add_product/',views.add_product, name='add_product'),
]

Ecommerce_site/Ecommerce_site/urls.py
from django.contrib import admin
from django.urls import path, include

# show media
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('account/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
]


# media
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Ecommerce_site/App_Order/models.py
# run migrations after completing full models.py
# 1. py manage.py makemigrations App_Order
# 2. py manage.py migrate
# add to admin.py to register

from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
# Model
from App_Shop.models import Product


# Create your models here.

class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="cart")
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    purchased =models.BooleanField(default=False)  # NOTE: cart e oi product thake ja purchase kora hyny, purchase hole ta r cart e thakena
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.quantity} X {self.item}'
    

    # calculate total price of a particular item
    # self.item.price ==> ekhane item inherit korse "Product" class k , Product class er "price" field
    def get_total(self):
        total = self.item.price * self.quantity
        float_total = format(total, '0.2f')     # 2 decimal places
        return float_total
    



# cart er shob item --> 1 order
# ManyToMany relation, cz, 
# (i) 1 cart er 1 item onekgulo order e thakte pare
# (ii) 1 order e onekgulo cart er item thakte pare
class Order(models.Model):
    orderitems = models.ManyToManyField(Cart)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)  # order kora hoye gese kina
    created = models.DateTimeField(auto_now_add=True)
    paymentId = models.CharField(max_length=264, blank=True, null=True)     # payment korar por ei id ashbe, tar age null
    orderId = models.CharField(max_length=200, blank=True)
    #coupon_code = models.CharField(max_length=100, blank=True)


    # return all product cost, calls get_total() for individual product and sum all results
    def get_totals(self):
        total = 0
        for order_item in self.orderitems.all():
            total += float(order_item.get_total())
        return total
    

class Coupon(models.Model):
    coupon_code=models.CharField(max_length=100, unique=True)
    coupon_percent = models.IntegerField(
        default=1,
        validators=[
            MaxValueValidator(100),    # set max Value
            MinValueValidator(1)       # set min Value
        ]
    )

    def __str__(self):
        return self.coupon_code

Ecommerce_site/App_Order/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Authentication
from django.contrib.auth.decorators import login_required

# Model
from App_Order.models import Cart, Order
from App_Shop.models import Product

# Messages
from django.contrib import messages

# Create your views here.

@login_required
def add_to_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)    # fetch the item using primary_key

    # check j cart e item already ase kina, na thakle create
    # oi user er e, purchased=False er jnno sudhu
    order_item = Cart.objects.get_or_create(item=item, user = request.user, purchased=False)

    order_qs = Order.objects.filter(user= request.user, ordered=False)
    # current user er kono incomplete order ase kina
    # order_qs[0] use kora hoise object k list e convert korte
    if order_qs.exists():
        order = order_qs[0]          # index 0 e incomplete order jeta "order" e save hoise

        # check if the current item is already in the order
        if order.orderitems.filter(item = item).exists():

            # item ase, new order ashse, tai quantity 1 barbe, order_item[0] use hoise object k list/dict e convert korte
            # TUPLE akare thakte pare, at a time 1 tai tuple thake, tai index=0 hole oitai peye jai
            # NOTE: 'quantity' models.py er 'Cart' class er ekta field
            order_item[0].quantity +=1  
            order_item[0].save()
            messages.info(request, "This item quantity was updated.")
            return redirect("App_Shop:home")
        
        else:   # item order e na thakle
            order.orderitems.add(order_item[0])
            messages.info(request, "This item was added to your cart.")
            return redirect("App_Shop:home")
        
    else: # kono inactive order nai
        #create new order and add item to that order
        order = Order(user= request.user)
        order.save()
        order.orderitems.add(order_item[0])
        messages.info(request, "This item was added to your cart.")
        return redirect("App_Shop:home")


# NOTE: order er kaj holo cart er shob item k bind kora


# Show cart items
@login_required
def cart_view(request):
    carts = Cart.objects.filter(user= request.user, purchased= False)
    orders = Order.objects.filter(user= request.user, ordered= False)

    if carts.exists() and orders.exists():
        order = orders[0]
        return render(request, 'App_Order/cart.html', context={'carts': carts, 'order': order})
    else:
        messages.warning(request, "You don't have any item in your cart!")
        return redirect("App_Shop:home")
    



@login_required
def remove_from_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered= False)

    # jodi nkono order thake
    if order_qs.exists():
        # check j item remove korbo ta order er vitor ase kina
        order = order_qs[0]
        if order.orderitems.filter(item = item).exists():
            
            order_item = Cart.objects.filter(item = item, user = request.user, purchased = False)[0]       # item khuje ber kora ei user er jnno, last e [0] to convert tuple to accessible item

            # remove from orderitem
            order.orderitems.remove(order_item)
            # delete from cart
            order_item.delete()

            messages.warning(request, "This item was removed from your cart")
            return redirect("App_Order:cart")

        else:
            messages.info(request, "This item was not in your cart")
            return redirect('App_Shop:home')

    else:
        messages.info(request, "You don't have an active order")
        return redirect("App_Shop:home")
    


# cart e '+' dle item quantity barbe
def increase_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered= False)

    # jodi nkono order thake
    if order_qs.exists():
        # j item increase hbe ta order er item e ase kina
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            # increase quantity
            order_item = Cart.objects.filter(item = item, user = request.user, purchased = False)[0]

            if order_item.quantity >= 1:
                order_item.quantity += 1
                order_item.save()
                messages.info(request, f"{item.name} quantity has been updated")
                return redirect("App_Order:cart")
            
        else:
            messages.info(request, f"{item.name} is not in your cart")
            return redirect("App_Shop:home")

    else:
        messages.info(request, "You don't have an active order")
        return redirect("App_Shop:home")
    



# cart e '-' dle item quantity kombe
def decrease_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered= False)

    # jodi nkono order thake
    if order_qs.exists():
        # j item increase hbe ta order er item e ase kina
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            
            order_item = Cart.objects.filter(item = item, user = request.user, purchased = False)[0]

            # decrease quantity
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
                messages.info(request, f"{item.name} quantity has been updated")
                return redirect("App_Order:cart")
            
            else:
                # mane item 1 tai silo, seta bad dle item cart/order theke remove hye jabe
                order.orderitems.remove(order_item)
                order_item.delete()
                messages.warning(request, f"{item.name} item has been removed from your cart")
                return redirect("App_Order:cart")

        else:
            messages.info(request, f"{item.name} is not in your cart")
            return redirect("App_Shop:home")

    else:
        messages.info(request, "You don't have an active order")
        return redirect("App_Shop:home")

Ecommerce_site/templates/App_Order/cart.html
{% extends 'base.html' %}
{% block body_block %}



<div class="container my-5">
    <div class="my-5">
        <h2>Your Cart</h2>
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col" width='15%'>#</th>
                <th scope="col">Product Name</th>
                <th scope="col">Quantity</th>
                <th scope="col" align="right">Price</th>
                <th scope="col">Remove</th>
            </tr>
        </thead>
        <tbody>
            {% for cart in carts %}
                <tr>
                    {% comment %}
                        # foorloop.counter for loop er current iteration number  print kore, soja kothay i=0,1,2,3...
                        # cart.item.name => item ->App_order er models.py er field,  name-> item  ForeignKey Product er(App_Shop.models), 'name' oi Product class er field 
                        # cart.quantity=> 'quantity' holo App_order er models.py er field
                    {% endcomment %}
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ cart.item.name }}</td>
                    <td>
                        {% comment %} +/- sign diye cart item barano/komano {% endcomment %}
                        <a class="mr-2" href="{% url 'App_Order:decrease' pk=cart.item.pk %}">
                            <span class="badge badge-light">
                                <i class="fas fa-minus"></i>
                            </span>
                        </a>

                        {{cart.quantity}}

                        <a class="mr-2" href="{% url 'App_Order:increase' pk=cart.item.pk %}">
                            <span class="badge badge-light">
                                <i class="fas fa-plus"></i>
                            </span>
                        </a>

                    </td>
                    {% comment %} cart.get_total and order.get_totals holo models.py er fn gulo(App_Order) {% endcomment %}
                    <td align="right">&#2547; {{cart.get_total}}</td>
                    <td><a href="{% url 'App_Order:remove' pk=cart.item.pk %}" class="btn btn-danger btn-sm">Remove From Cart</a></td>
                </tr>
                {% endfor %}
               
                <tr>
                    <th scope="row"></th>
                    <td colspan="2">Total</td>     <!-- colspan diye 3 column jayga dokhol korse-->
                    <td align="right">&#2547; {{order.get_totals| floatformat:2 }}</td>
                    <td></td>
                </tr>
                <tr>
                    <th scope="row"></th>
                    <td colspan="4" class="text-right">
                        <a href="{% url 'App_Shop:home' %}" class="btn btn-warning mr-4">Continue Shopping</a>
                        <a href="{% url 'App_Payment:checkout' %}" class="btn btn-success mr-4">Proceed To Checkout</a>
                    </td>
                </tr>         
        </tbody>
    </table>
</div>




{% endblock %}