Ecommerce_site/App_Payment/urls.py
from django.urls import path
from App_Payment import views

app_name="App_Payment"

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('pay/', views.payment, name='payment'),
    path('status/', views.complete, name='complete'),
    path('purchase/<val_id>/<tran_id>/', views.purchase, name='purchase'),
    path('orders/', views.order_view, name='orders'),
]

Ecommerce_site/App_Shop/urls.py
from django.urls import path
from App_Shop import views


app_name = 'App_Shop'



urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
    path('add_product/',views.add_product, name='add_product'),
]

Ecommerce_site/Ecommerce_site/urls.py
from django.contrib import admin
from django.urls import path, include

# show media
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('account/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
]


# media
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Ecommerce_site/App_Payment/models.py
# migrate after completing models.py
# 1. py manage.py makemigrations App_Payment
# 2. py manage.py migrate

from django.db import models
from django.conf import settings

# Create your models here.

class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    address = models.CharField(max_length=264, blank=True)
    zipcode = models.CharField(max_length=10, blank=True)
    city = models.CharField(max_length=30, blank=True)
    country = models.CharField(max_length=30, blank=True)


    def __str__(self):
        return f'{self.user.profile.username} billing address'
    
    # check all fields are filled 
    def is_fully_filled(self):
        field_names = [f.name for f in self._meta.get_fields()]

        for field_name in field_names:
            value = getattr(self, field_name)

            if value is None or value =='':
                return False
        
        return True
    
    class Meta:
        verbose_name_plural = 'Billing Addresses'

Ecommerce_site/App_Payment/forms.py
from django import forms
from App_Payment.models import BillingAddress




class BillingForm(forms.ModelForm):
    class Meta:
        model = BillingAddress
        fields = ['address','zipcode','city','country',]


class CollectCouponForm(forms.Form):
    collect = forms.CharField(
        required=False,
        label="",
        widget=forms.TextInput(attrs={'placeholder':'Enter Coupon'})
    )

Ecommerce_site/App_Payment/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.contrib import messages
from django.urls import reverse

#models and forms
from App_Order.models import Order, Cart, Coupon
from App_Payment.forms import BillingAddress, BillingForm, CollectCouponForm

from django.contrib.auth.decorators import login_required

# payment sslcommerz
# documentation to use in project: https://pypi.org/project/sslcommerz-python/#:~:text=install%20sslcommerz%2Dpython-,Projected%20use,-from%20sslcommerz_python.payment
import requests
import socket
from sslcommerz_python.payment import SSLCSession
from decimal import Decimal

# avoid csrf verification
from django.views.decorators.csrf import csrf_exempt

# views

coupon_percentise = 0



@login_required
def checkout(request):
    saved_address = BillingAddress.objects.get_or_create(user= request.user)
    saved_address = saved_address[0]        # touple to object

    form = BillingForm(instance= saved_address)  # already save kora adds er upor form generate hbe, save na thakle blank form

    coupon_form = CollectCouponForm()
    global coupon_percentise
    coupon_percentise = 0

    
    if request.method == 'POST':
        form_name = request.POST.get('form_name')


        if form_name == 'address_form':
            form = BillingForm(request.POST, instance=saved_address)

            if form.is_valid():
                form.save()
                form = BillingForm(instance=saved_address)
                messages.success(request, f"Shipping Address Saved!")


        
        
        elif form_name == 'coupon_form':
            coupon_form = CollectCouponForm(request.POST)

            if coupon_form.is_valid():      
                collect_code = coupon_form.cleaned_data['collect']  #or, collect_code = coupon_form.cleaned_data.get('collect')
                
                try:
                    
                    coupon = Coupon.objects.get(coupon_code=collect_code)
                    coupon_percentise = coupon.coupon_percent
                    messages.success(request, f"Coupon Applied")

                except Coupon.DoesNotExist:
                    coupon_percentise = 0
                    messages.warning(request, f"Invalid coupon code")


    # show ordered items in checkout page
    order_qs = Order.objects.filter(user = request.user, ordered = False)
    order_items = order_qs[0].orderitems.all()          # 'orderitems' models.py er ekta field(App_Order)
    order_total = order_qs[0].get_totals()              # 'get_totals' models.y er ekta fn

    order_total_after_coupon_applied = 0

    if coupon_percentise > 0:
        order_total_after_coupon_applied = order_total-((order_total * coupon_percentise)/100)
    

    return render(request, 'App_Payment/checkout.html', 
                  context={
                      'form': form,
                      'order_items': order_items,
                      'order_total': order_total,
                      'saved_address': saved_address,
                      'coupon_form': coupon_form,
                      'order_total_after_coupon_applied' : order_total_after_coupon_applied,
                    })







'''
real one
'''   

# @login_required
# def checkout(request):
#     saved_address = BillingAddress.objects.get_or_create(user= request.user)
#     saved_address = saved_address[0]        # touple to object

#     form = BillingForm(instance= saved_address)  # already save kora adds er upor form generate hbe, save na thakle blank form
    
#     if request.method == 'POST':
#         form = BillingForm(request.POST, instance=saved_address)

#         if form.is_valid():
#             form.save()
#             form = BillingForm(instance=saved_address)
#             messages.success(request, f"Shipping Address Saved!")

#     # show ordered items in checkout page
#     order_qs = Order.objects.filter(user = request.user, ordered = False)
#     order_items = order_qs[0].orderitems.all()          # 'orderitems' models.py er ekta field(App_Order)
#     order_total = order_qs[0].get_totals()              # 'get_totals' models.y er ekta fn
    

#     return render(request, 'App_Payment/checkout.html', 
#                   context={
#                       'form': form,
#                       'order_items': order_items,
#                       'order_total': order_total,
#                       'saved_address': saved_address,
#                     })







# view for payment
@login_required
def payment(request):
    saved_address = BillingAddress.objects.get_or_create(user = request.user)
    saved_address = saved_address[0]

    # check all fields are filled //models.py
    if not saved_address.is_fully_filled():
        messages.info(request, f"Please complete shipping address!")
        return redirect("App_Payment:checkout")
    
    # App_login er modles.py er fn, "profile"==related_name
    if not request.user.profile.is_fully_filled():
        messages.info(request, f"Please complete profile detail")
        return redirect('App_Login:profile')
    
    # https://pypi.org/project/sslcommerz-python/

    #---------------------------- info-1:  mypayment ------------------------#
    #  sandbox na hoye real payment hole "sslc_is_sandbox=False", "sslc_store_id" & "sslc_store_pass" check from reply email from sslcoomerz, 
    mypayment = SSLCSession(sslc_is_sandbox=True, sslc_store_id='abcco656cf6297a654', sslc_store_pass='abcco656cf6297a654@ssl')
    

    #---------------------------- info-2: mypayment.set_urls() ------------------------#

    '''
    status_url = request.build_absolute_uri()
    # eta current view er url k call kore
    print(status_url)   #o/p: http://127.0.0.1:8000/payment/pay/
    '''
    status_url = request.build_absolute_uri(reverse("App_Payment:complete"))

    # print(status_url)   #http://127.0.0.1:8000/payment/status/

    #'success_url' payment success hole kon page e jabe, fail/cancel hole kon page, 'ipn_url'= special kono notification thakle kon page
    # we'll use a template here
    mypayment.set_urls(success_url=status_url, fail_url= status_url, cancel_url= status_url, ipn_url = status_url)



    #---------------------------- info-3:  mypayment.set_product_integration() ------------------------#
    # product info

    order_qs = Order.objects.filter(user = request.user, ordered= False)
    order_items = order_qs[0].orderitems.all()
    order_items_count = order_qs[0].orderitems.count()
    order_total = order_qs[0].get_totals()  # get_totals() is a fn from models.py

    if coupon_percentise > 0:
        order_total = order_total-((order_total * coupon_percentise)/100)
    
    mypayment.set_product_integration(total_amount=Decimal(order_total), currency='BDT', product_category='Mixed', product_name= order_items, num_of_item=order_items_count, shipping_method='Courier', product_profile='None')



    #---------------------------- info-3:  mypayment.set_customer_info() ------------------------#
    # kono ekta field blank thakle error dekhabe, ejnno upore egula chk kora hoise

    current_user = request.user
    # 'profile' == related_name
    mypayment.set_customer_info(name= current_user.profile.full_name, email= current_user.email, address1= current_user.profile.address_1, address2= current_user.profile.address_1, city= current_user.profile.city, postcode= current_user.profile.zipcode, country= current_user.profile.country, phone= current_user.profile.phone)

 

    #---------------------------- info-3:  mypayment.set_shipping_info() ------------------------#
    # Billing info
    mypayment.set_shipping_info(shipping_to= current_user.profile.full_name, address= saved_address.address, city= saved_address.city, postcode= saved_address.zipcode, country= saved_address.country)


    # If you want to post some additional values
    # mypayment.set_additional_values(value_a='cusotmer@email.com', value_b='portalcustomerid', value_c='1234', value_d='uuid')


    response_data = mypayment.init_payment()
    #print(response_data)    #{'status': 'SUCCESS', 'sessionkey': '86A9ED514AFD61A49124ED056FBBD665', 'GatewayPageURL': 'https://sandbox.sslcommerz.com/EasyCheckOut/testcde86a9ed514afd61a49124ed056fbbd665'}


    # see the print(response_data) output to understand dict key 'GatewayPageURL'
    # redirected to sslcommerz payment system
    return redirect(response_data['GatewayPageURL'])



# accessing complete.html template// payment status (success/failure etc)
# payment er pore info ei page dekhabe
# @csrf_exempt deyar karone bangking er porer page(after pressing "success"/"successwith risk"/"failed" in payment bank/mobile_bank page)  e "post" method e ahob banking info gulo django show korbe(debug panel e ,error hole)
@csrf_exempt
def complete(request):

    if request.method=='post' or request.method=='POST':
        payment_data = request.POST
        status = payment_data['status']
        

        if status=='VALID':
            val_id = payment_data['val_id']
            tran_id = payment_data['tran_id']
            messages.success(request, f"Your Payment Completed Successfully! Page will be redirected!")

            # call purchase()
            return HttpResponseRedirect(reverse('App_Payment:purchase', kwargs={'val_id':val_id, 'tran_id':tran_id},))

        else:
            messages.warning(request, f"Your Payment Failed! Please Try Again! Page will be redirected!")


    return render(request, 'App_Payment/complete.html', context = {})


# purchase korar por cart clear korbe
# order er ordered=True and cart er purchased = True hbe
@login_required
def purchase(request, val_id, tran_id):

    order_qs = Order.objects.filter(user=request.user, ordered=False)
    order = order_qs[0]

    order.ordered = True
    order.orderId = tran_id
    order.paymentId = val_id
    order.save()

    cart_items= Cart.objects.filter(user=request.user, purchased=False)

    for item in cart_items:
        item.purchased = True
        item.save()

Ecommerce_site/templates/App_Payment/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}


<div class="container mt-5">
    <h2 class="mb-3">
        Shipping Address <span class"text-muted">Checkout</span>
    </h2>
    <div class="row">
        <div class="col-md-9">
            <div class="card mb-5" style="height: auto">
                <div class="card-body">
                    <form method='POST'>
                        {{form|crispy}}

                        <input type="hidden" name="form_name" value="address_form">

                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary float-right">Save Address</button>

                    </form>
                </div>
            </div>
        </div>
        {% comment %} show ordered items {% endcomment %}
        <div class="col-md-3">
            <div class="card" style="height: auto">
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        {% for order_item in order_items %}
                            <li class="list-group-item">{{ order_item.item.name }} x {{order_item.quantity}}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="card-footer">
                    <span class="float-left"><b>Order Total</b></span>

                    {% if order_total_after_coupon_applied != 0 %}
                        
                        <span class="float-right"><b>&#2547;  <strike style="color:red">{{order_total|floatformat:2 }} </strike></b></span>
                       
                        <span class="float-right"><b>&#2547; {{order_total_after_coupon_applied|floatformat:2 }}</b></span>
                    {% else %}
                        <span class="float-right"><b>&#2547; {{order_total|floatformat:2 }}</b></span>
                    {% endif %}

                </div>
            </div>
            <br><br>

            {% comment %} coupon {% endcomment %}
            <div>
                <form method="post">
                    {{coupon_form|crispy}}

                    <input type="hidden" name="form_name" value="coupon_form">

                    {% csrf_token %}
                    <button type="submit" class="btn btn-info float-right">Apply</button>
                </form>
            </div>
            <br><br>
            {% comment %} coupon {% endcomment %}

            
            {% comment %} address er protita input field fill korse kina?, models.py e is_fully_filled fn ase {% endcomment %}
            {% if saved_address.is_fully_filled %}
                <a href="{% url 'App_Payment:payment' %}" class="btn btn-warning btn-md">Make Payment</a>
            {% else %}
                <div class="alert alert-info">
                    <p>Please fill up all the information to make payment</p>
                </div>
            {% endif %}

        </div>
    </div>
</div>

<br><br>

{% endblock%}

Ecommerce_site/templates/App_Payment/complete.html
<!-- external page hisebe count hbe -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% comment %} page will be refreshed and redirected to given url after 5 sec {% endcomment %}
    <meta http-equiv="refresh" content="5; url={% url 'App_Shop:home' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <!-- bootstrap -->
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
     integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Payment Status</title>
</head>
<body>
    <div class="container">
        <div class="message container mt-2">
            {% if messages %}
                {% for message in messages %}
                    <div {% if message.tags %} class="alert alert-{{message.tags}}{% endif %}" role="alert">
                        {{message}}
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</body>
</html>

Ecommerce_site/templates/App_Payment/order.html
{% extends 'base.html' %}
{% block body_block %}


<div class="container mt-5">
    <h2 class="text-center"><string>Your Orders</string></h2>
    <div class="row">
        <div class="col-md-12">
            <div class="card mt-5" style="height:auto">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Order Id</th>
                                <th scope="col">Products</th>
                                <th scope="col">Status</th>              
                            </tr>
                        </thead>

                        <tbody>
                            {% for order in orders %}
                                <tr>
                                    <th scope="row">{{ forloop.counter }}</th>
                                    <td><a href="#">{{ order.orderId }}</a></td>
                                    <td>
                                        {% for item in order.orderitems.all %}
                                            {{item}}
                                            <br>
                                        {% endfor %}
                                    </td>
                                    <td>
                                        <span class="badge badge-primary">Processing Your Order</span>
                                    </td>
                                </tr>

                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-12 my-5 text-center">
            <a href="{% url 'App_Shop:home' %}">Back to Home</a>
        </div>
    </div>
</div>


{% endblock %}