Ecommerce_site/App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name='add'),
    path('remove/<pk>/', views.remove_from_cart, name='remove'),
    path('cart/', views.cart_view, name='cart'),
    path('increase/<pk>/', views.increase_cart, name='increase'),
    path('decrease/<pk>/', views.decrease_cart, name='decrease'),
]

Ecommerce_site/App_Shop/urls.py
from django.urls import path
from App_Shop import views


app_name = 'App_Shop'



urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
    path('add_product/',views.add_product, name='add_product'),
]

Ecommerce_site/Ecommerce_site/urls.py
from django.contrib import admin
from django.urls import path, include

# show media
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('account/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
]


# media
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Ecommerce_site/App_Shop/models.py
# run migrations after completing models.py
# 1. py models.py makemigrations "App_Shop"
# py manage.py migrate
from django.db import models
from App_Login.models import User

# Create your models here.

# product categories
class Category(models.Model):
    title = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        # normally admin panel theke dekhle class er por "s" jog kore dey: means=> Category + s =Categorys
        # verbose_name_plural dle admin panel theke oi name tai show korbe
        verbose_name_plural = "Categories"



class Product(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name='related_name_product_seller')
    mainimage = models.ImageField(upload_to="Products")
    name = models.CharField(max_length=264)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    preview_text = models.TextField(max_length=200, verbose_name='Preview Text') # short description of product
    detail_text = models.TextField(max_length=1000, verbose_name='Description')
    price = models.FloatField()
    old_price = models.FloatField(default= 0.0)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-created',]

                                    

Ecommerce_site/App_Shop/forms.py
from django import forms
from App_Shop.models import Product


# modify model structure
class AddProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ['name','category','mainimage','preview_text','detail_text','price','old_price']
        

Ecommerce_site/App_Shop/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse

# import views
from django.views.generic import ListView, DetailView

#Models
from App_Shop.models import Product

# Mixin
from django.contrib.auth.mixins import LoginRequiredMixin


# add product
from App_Shop.forms import AddProductForm
from django.contrib.auth.decorators import login_required



# Create your views here.

# display products
class Home(ListView):
    # NOTE: ListView e context hisebe object_name set na korle by default 'object_list' name edata pass hy template e
    model = Product
    template_name = 'App_Shop/home.html'



class ProductDetail(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'App_Shop/product_detail.html'



@login_required
def add_product(request):
    form = AddProductForm()
    if request.method == 'POST':
        form = AddProductForm(request.POST, request.FILES)

        if form.is_valid():
            
            product = form.save(commit = False)
            product.seller = request.user
            product.save()

            return HttpResponseRedirect(reverse('App_Shop:home'))

    return render(request, 'App_Shop/add_product.html', context={'form': form})

Ecommerce_site/templates/App_Shop/add_product.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}

{% if user.is_authenticated and user.account_type == "Seller" %}
    <center>
        <h3 style="color:orange">Add Product</a></h3>
    </center>

    <br>

    <form method='post' enctype='multipart/form-data'>
        
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-warning btn-sm">Add Product</button>
    </form>
<br><br>


{% endif %}
{% endblock %}

Ecommerce_site/templates/App_Shop/home.html
<!-- display products -->
{% extends 'base.html' %}
{% block body_block %}

{% if user.is_authenticated and user.account_type == "Seller" %}
    <center>
        <h5><p style="color:orange">Give advertise of your product</p>&nbsp;<a href="{% url 'App_Shop:add_product' %}" class="btn btn-primary">Advertise</a></h5>
        
    </center>
{% endif %}

<!-- "my-5" is for margin-->
<div class="conatiner my-5">
    <h2 class="my-5">Featured Products</h2>
    <div class='row'>
        {% comment %} NOTE: ListView e context hisebe object_name set na korle by default 'object_list' name edata pass hy template e {% endcomment %}
        {% for product in object_list %}

            <!--
                # screen size md==medium hole screen 2 part
                # small hole 1 part
                # large hole 3 part
                e vag hbe
            -->
            <div class="col-md-6 col-sm-12 col-lg-3">
                {% comment %} base.html e css code ache for the classes {% endcomment %}
                <figure class="card card-product">
                    <div class="img-wrap">
                        <img src="/media/{{product.mainimage}}" style="width:100%; height:300px">
                    </div>
                    <figcaption class="info-wrap">

                        <h6 class="title">
                            <a href="{% url 'App_Shop:product_detail' pk=product.pk %}">{{product.name}}</a>
                        </h6>
                        <div class="action-wrap">
                            <div class="price-wrap h5">
                                <!--
                                    html e TK. er code= &#2547;
                                    floatformat:2== 2 decimal point porjnto show
                                -->
                                <span class="price-new">&#2547; {{product.price|floatformat:2}}</span>
                                <span class="price-old">
                                    {% comment %} <strike> means old price kete dbe {% endcomment %}
                                    <strike>
                                        &#2547; {{product.old_price|floatformat:2}}
                                    </strike>
                                </span>
                            </div>
                        </div>

                    </figcaption>
                </figure>
            </div>

        {% endfor %}

    </div>
</div>


{% endblock %}

Ecommerce_site/templates/App_Shop/product_detail.html
{% extends 'base.html'%}
{% block body_block %}
    
    <div class="conatiner my-5">
        <div class="card">
            <div class="row">
                {% comment %}
                    <aside> measns pashapashi dekhay
                    <article> view change kore
                {% endcomment %}
                <aside class="col-sm-5 border-right">
                    <article class="gallery-wrap">
                        <div class="img-big-wrap">
                            <div>
                                <a href="#">
                                    <img src="/media/{{object.mainimage}}" style="width: 450px">
                                </a>
                            </div>
                        </div>
                    </article>
                </aside>
                <aside class="col-sm-7">
                    <article class="card-body p-5">
                        <h3 class="title mp-3">{{object.name}}</h3>
                        <p style="color:blue"><strong>Seller: {{object.seller.profile.full_name}}</strong></p>
                        <p class="price-detail-wrap">
                            <span class="price h3 text-warning">
                                <span class="currency">BDT &#2547;</span>
                                <span class="num">{{object.price}}</span>
                            </span>
                        </p>

                        {% comment %}
                            dl = description list
                            dt= description truncatechars_html
                            dd = description description
                        {% endcomment %}

                        <dl class="item-property">
                            <dt>Description</dt>
                            <dd>
                                <p>{{object.detail_text|linebreaks}}</p>
                            </dd>
                        </dl>
                        <a href="{% url 'App_Order:add' pk=object.pk %}" class="btn btn-lg btn-outline-primary text-uppercase">
                            <i class="fas fa-shopping-cart"></i>Add to cart
                        </a>
                    </article>
                </aside>
            </div>
        </div>
    </div>


{% endblock %}